/**
 * Server-only country data (D-13). Both files are generated by tools/build-geo.mjs
 * and bundled with the function; nothing here is ever sent to the client except
 * the one path that `getRound` inlines for the current round (SEC-2).
 */

import countriesJson from "../data/countries.json";
import shapesJson from "../data/shapes.json";
import type { LonLat } from "./geo";

export interface Country {
  code: string;
  code3: string;
  names: { en: string; "pt-BR": string };
  /**
   * The capital city, the `capital` challenge kind's prompt (FR-8).
   * Server-only for the same reason as the centroid: a capital→country map on
   * the client would name the answer in one lookup (SEC-2), which is why
   * tools/build-geo.mjs writes this field here and not into
   * site/data/countries.min.json.
   */
  capital: { en: string; "pt-BR": string };
  /** [lon, lat] of the retained landmass (03-geo-data-pipeline.md §3.2) */
  centroid: LonLat;
  tier: 1 | 2 | 3;
}

export interface Shape {
  viewBox: string;
  d: string;
  fillRule: "evenodd";
}

const list = (countriesJson as unknown as { countries: Country[] }).countries;
const shapes = shapesJson as unknown as { viewBox: string; fillRule: "evenodd"; shapes: Record<string, string> };

export const COUNTRIES: ReadonlyMap<string, Country> = new Map(list.map((c) => [c.code, c]));

export function countryByCode(code: string): Country | undefined {
  return COUNTRIES.get(code);
}

/** The silhouette for one country, or undefined if the build never produced one. */
export function shapeFor(code: string): Shape | undefined {
  const d = shapes.shapes[code];
  return d === undefined ? undefined : { viewBox: shapes.viewBox, d, fillRule: shapes.fillRule };
}
