/**
 * Server-only country data (D-13). The files are generated by tools/build-geo.mjs
 * and tools/build-flags.mjs and bundled with the function; nothing here is ever
 * sent to the client except the one shape `getRound` inlines for the current
 * round, and the one flag a `flag` challenge inlines for the current item (SEC-2).
 */

import countriesJson from "../data/countries.json";
import shapesJson from "../data/shapes.json";
import flagsJson from "../data/flags.json";
import gdpJson from "../data/gdp.json";
import type { LonLat } from "./geo";

export interface Country {
  code: string;
  code3: string;
  names: { en: string; "pt-BR": string };
  /**
   * The capital city, the `capital` challenge kind's prompt (FR-8).
   * Server-only for the same reason as the centroid: a capital→country map on
   * the client would name the answer in one lookup (SEC-2), which is why
   * tools/build-geo.mjs writes this field here and not into
   * site/data/countries.min.json.
   */
  capital: { en: string; "pt-BR": string };
  /** [lon, lat] of the retained landmass (03-geo-data-pipeline.md §3.2) */
  centroid: LonLat;
  tier: 1 | 2 | 3;
}

export interface Shape {
  viewBox: string;
  d: string;
  fillRule: "evenodd";
}

/**
 * One flag, flattened to filled paths by tools/build-flags.mjs (OQ-11). Data,
 * not markup: the client builds one <path> per entry and sets these attributes
 * on it, so nothing that arrives here is ever parsed as HTML or SVG source.
 * `clip` is a path's own clip, and `renderFlag` clips the whole flag to its
 * viewBox — which is what makes the build safe to drop a clip that covers it.
 */
export interface FlagPath {
  d: string;
  clip?: string;
  transform?: string;
  fill?: string;
  fillRule?: string;
  fillOpacity?: string;
  stroke?: string;
  strokeWidth?: string;
  strokeLinecap?: string;
  strokeLinejoin?: string;
  strokeMiterlimit?: string;
  strokeOpacity?: string;
  strokeDasharray?: string;
  opacity?: string;
}

export interface Flag {
  viewBox: string;
  paths: FlagPath[];
}

const list = (countriesJson as unknown as { countries: Country[] }).countries;
const shapes = shapesJson as unknown as { viewBox: string; fillRule: "evenodd"; shapes: Record<string, string> };
const flags = (flagsJson as unknown as { flags: Record<string, Flag> }).flags;
const gdp = gdpJson as unknown as { year: number; values: Record<string, number> };

/**
 * The year every `gdp` challenge asks about (D-53). Pinned and shown in the
 * prompt: "the GDP of Argentina" is not a stable number, and an unstated
 * vintage is an argument waiting to happen.
 */
export const GDP_YEAR: number = gdp.year;

export const COUNTRIES: ReadonlyMap<string, Country> = new Map(list.map((c) => [c.code, c]));

export function countryByCode(code: string): Country | undefined {
  return COUNTRIES.get(code);
}

/** The silhouette for one country, or undefined if the build never produced one. */
export function shapeFor(code: string): Shape | undefined {
  const d = shapes.shapes[code];
  return d === undefined ? undefined : { viewBox: shapes.viewBox, d, fillRule: shapes.fillRule };
}

/**
 * The flag for one country, or undefined when the build dropped it — over the
 * byte budget, needing artwork the flat format cannot carry, or excluded by
 * hand because the coat of arms spells the country's name (tools/flags.json).
 * Twenty-four of the pool's 196 have no flag; `flag.pool()` is what that means
 * for play.
 */
export function flagFor(code: string): Flag | undefined {
  return flags[code];
}

/**
 * GDP per capita, PPP, in current international dollars, for `GDP_YEAR`
 * (D-53). Undefined for the ten countries the World Bank has no figure for —
 * Cuba, Eritreia, Coreia do Norte, Liechtenstein, Mônaco, Sudão do Sul, Síria,
 * Taiwan, Venezuela and Iêmen — which is what keeps them out of `gdp.pool()`.
 */
export function gdpFor(code: string): number | undefined {
  return gdp.values[code];
}
