#!/usr/bin/env node
// GDP build: World Bank → the one file the `gdp` kind serves from (OQ-12, D-53).
// See 06-tournaments.md §5.4.
//
//   node build-gdp.mjs [--year 2023]
//
// Output: backend/functions/src/data/gdp.json — server-only, committed.
//
// Unlike the geo and flag builds this one reads the network, because the World
// Bank is an API rather than an npm package. That is why the OUTPUT is the
// vendored artefact and is committed: a rebuild needs connectivity, and every
// figure the game serves is in git where it can be diffed.
//
// **A rebuild can legitimately change numbers.** The World Bank revises past
// years for a long time after they close, which is exactly why D-53 pins a
// single year and puts it in the prompt. A diff here is a revision, not a bug —
// read it, then commit it.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parseArgs } from "node:util";

const TOOLS = dirname(fileURLToPath(import.meta.url));
const ROOT = join(TOOLS, "..");
const read = (p) => JSON.parse(readFileSync(join(ROOT, p), "utf8"));
const write = (p, data) => {
  mkdirSync(dirname(join(ROOT, p)), { recursive: true });
  writeFileSync(join(ROOT, p), data);
};

const { values: args } = parseArgs({ options: { year: { type: "string", default: "2023" } } });
const YEAR = Number(args.year);

// D-53: GDP per capita, PPP, current international $. Chosen over the three
// alternatives because it is the only one a player can reason about without
// already knowing the answer — a 131x spread against 520 000x for total GDP,
// and it asks "how rich is this place" rather than "how many people live here".
const INDICATOR = "NY.GDP.PCAP.PP.CD";
const MIN_POOL = 170;

/** The World Bank spells Kosovo XKX; world-countries gives it UNK. */
const ISO3_OVERRIDES = { XK: "XKX" };

const countries = read("backend/functions/src/data/countries.json").countries;
const iso3 = (c) => ISO3_OVERRIDES[c.code] ?? c.code3;
const byIso3 = new Map(countries.map((c) => [iso3(c), c]));

const url = `https://api.worldbank.org/v2/country/all/indicator/${INDICATOR}?format=json&per_page=20000&date=${YEAR}`;
const res = await fetch(url);
if (!res.ok) throw new Error(`World Bank returned ${res.status} for ${url}`);
const [meta, rows] = await res.json();
if (!Array.isArray(rows)) throw new Error(`unexpected response: ${JSON.stringify(meta)}`);
if (meta.pages > 1) throw new Error(`${meta.pages} pages — raise per_page`);

const values = {};
for (const row of rows) {
  const country = byIso3.get(row.countryiso3code);
  if (!country || row.value === null) continue;
  const v = Math.round(row.value);
  if (!Number.isFinite(v) || v <= 0) throw new Error(`${country.code}: implausible value ${row.value}`);
  values[country.code] = v;
}

const kept = Object.keys(values).sort();
const missing = countries.filter((c) => values[c.code] === undefined);

const out = {
  "//": `GDP per capita, PPP (current international $), ${YEAR}, from the World Bank indicator ${INDICATOR}. Generated by tools/build-gdp.mjs. Server-only: the figure is the answer. Do not edit by hand.`,
  source: {
    name: "World Bank, World Development Indicators",
    indicator: INDICATOR,
    url: `https://data.worldbank.org/indicator/${INDICATOR}`,
    license: "CC BY 4.0. See NOTICE.",
    retrievedAt: new Date().toISOString().slice(0, 10),
  },
  year: YEAR,
  values: Object.fromEntries(kept.map((c) => [c, values[c]])),
};

console.log(`gdp: ${kept.length} of ${countries.length} countries, ${YEAR}, ${INDICATOR}`);
const sorted = kept.map((c) => [c, values[c]]).sort((a, b) => a[1] - b[1]);
console.log(`  range: ${sorted[0][1].toLocaleString("en")} (${sorted[0][0]}) … ${sorted.at(-1)[1].toLocaleString("en")} (${sorted.at(-1)[0]})  — ${(sorted.at(-1)[1] / sorted[0][1]).toFixed(0)}x`);
console.log(`  no figure for ${missing.length}: ${missing.map((c) => c.names["pt-BR"]).join(", ")}`);

if (kept.length < MIN_POOL) throw new Error(`only ${kept.length} countries have a figure; the floor is ${MIN_POOL}`);

write("backend/functions/src/data/gdp.json", JSON.stringify(out, null, 0) + "\n");
console.log("  written: backend/functions/src/data/gdp.json");
